CC=gcc
CFLAGS=-I./src -Wall -Wextra -pedantic -std=c99

SRC=src/kilo.c
OBJ=src/kilo.o

kilo: $(OBJ)
	$(CC) $(OBJ) -o kilo $(CFLAGS)
src/%.o: src/%.c
	$(CC) -c $< -o $@ $(CFLAGS)
clean:
	rm -f src/*.o kilo